### ISSUE TITLE
Build landing page out with a static site gen (gatsby, next, etc.)

### ISSUE THREAD

**Issue by evanpipta** [mithraiclabs/psyoptions-frontend#564]
[Figma Design](https://www.figma.com/file/2IQG9iDDbuA4PLnS6G9e9C/Homepage?node-id=19%3A6)

- [ ] Start repo and add static site gen tools / build 

- [ ] Build the landing page sections html/css

- [ ] Set up page on psyoptions.io with aws CloudFormation and retire main landing page from frontend app

**Comment by tomjohn1028** [comment]
This has been assigned out to an external collaborator. I'll move to in progress
