### ISSUE TITLE
Add Multi-close functionality  

### ISSUE THREAD

**Issue by stockmart** [mithraiclabs/psyoptions-frontend#588]
Users can write x amount of options at once, but cannot claim assets from multiple exercised contracts at once. 

Link to the users issue: https://discord.com/channels/821571258852442142/821594431119425586/889779947105816586

**Comment by tomjohn1028** [comment]
> is there a way to claim quote all contracts that have been exercised? I am the one who wrote the option. and it is ridiculous that I was able to write 10 contracts at once but I am not able to claim quote all (that were exercised) at once
