### ISSUE TITLE
Moving the asset filtering section to the far left side

### ISSUE THREAD

**Issue by HypeQuant** [mithraiclabs/psyoptions-frontend#730]
It's currently not intuitive since filtering for assets is generally the first step and people tend to look at things from left to right. 
![Screen Shot 2021-11-17 at 10 58 35 AM](https://user-images.githubusercontent.com/94559273/142256462-ae9bf1e9-5e21-489d-8fdd-fd153f035516.png)

**Comment by 0xbenchy** [comment]
Bumping this, also think this is an important/easy fix

**Comment by Taylor123** [comment]
Thanks for the bump @0xbenchy. Will fix today
