### ISSUE TITLE
Display issues when settling funds

### ISSUE THREAD

**Issue by stockmart** [mithraiclabs/psyoptions-frontend#737]
![image](https://user-images.githubusercontent.com/71112484/142768765-a14e057c-0fb7-47a8-b73a-1633498b2651.png)
![image](https://user-images.githubusercontent.com/71112484/142768768-fd888e34-1a80-460d-8c57-7d90d04a9624.png)

**Comment by T-Wall** [comment]
Not only the settling funds but the amount of collateral need to lock to mint is wrong on staging
