### ISSUE TITLE
Error Selling CALLS/PUTS

### ISSUE THREAD

**Issue by T-Wall** [mithraiclabs/psyoptions-frontend#742]
When minting limit call options on the NOV. 26th BTC 60k, 70k strike market I am receiving an unknown error

Minting Put options on NOV. 26th BTC 50k, 52k and 65k strike receives error

Used amounts ranging from 1-100 with the same error
<img width="966" alt="Screen Shot 2021-11-22 at 5 31 11 PM" src="https://user-images.githubusercontent.com/91228741/142954885-93628f5a-7529-405b-9da8-728684fc45f2.png">

<img width="966" alt="Screen Shot 2021-11-22 at 5 20 19 PM" src="https://user-images.githubusercontent.com/91228741/142954105-1e259bb5-42b8-422d-a0a5-d41b8299d192.png">

<img width="966" alt="Screen Shot 2021-11-22 at 5 23 44 PM" src="https://user-images.githubusercontent.com/91228741/142954370-b98b4fe5-cbe8-4ef1-8625-3c858421d0c9.png">
>
<img width="966" alt="Screen Shot 2021-11-22 at 5 27 21 PM" src="https://user-images.githubusercontent.com/91228741/142954617-5d047f22-2e16-46ea-881a-a2d4b22d37ea.png">

<img width="966" alt="Screen Shot 2021-11-22 at 5 28 27 PM" src="https://user-images.githubusercontent.com/91228741/142954710-ddbffc31-670b-4d65-b66b-6128fc2fd7ed.png">

**Comment by tomjohn1028** [comment]
Possibly the same as https://github.com/mithraiclabs/psyoptions-frontend/issues/739
