### ISSUE TITLE
Consider adding indicator when in restricted jurisdiction, explaining why MainNet is not an option

### ISSUE THREAD

**Issue by jasonhargrove** [mithraiclabs/psyoptions-frontend#744]
# Problem

Previously when a person in a restricted jurisdiction visited the trading app they were presented an `access denied` screen. We wanted to soften this, so the first change moved this to the `wallet connection`. Thus only when connecting, they would receive the access denied message

The second iteration removed the `access denied` screen entirely, instead, defaulting to `DevNet`. Much friendlier, and more importantly, allows everyone to use DevNet. But in the change, it's potentially confusing.

- it suggests we are only on DevNet
- for those who are traveling, or using VPNs, it could be confusing
- for the dev team it could be confusing

# Potential Solutions

- add mainnet to the menu again, but disable it and grey it out
- and / or, add some kind of alert or message

The message should then show a friendly version of the previous `access denied` page which explains why they are unable to access MainNet from that location

**Comment by tomjohn1028** [comment]
I think mainnet should be added to the menu, but users cannot connect their wallet (current wallets are disconnected). People like to see the state of the order books and we should not block that. I would reference Mango as a good example again. Visitors can see the entire app on mainnet, but they cannot connect their wallet
