### ISSUE TITLE
Nothing shown 

### ISSUE THREAD

**Issue by joeywongt3ch** [mithraiclabs/psyoptions-frontend#780]
When I select eth as asset, I select the date, but nothing shown in ALL dates. 
Supposed there's some due on Dec 31.

![Screenshot_20211223-153529~2](https://user-images.githubusercontent.com/49179952/147205554-268776bd-675c-4e54-b4d6-6782c991b542.png)

**Comment by Taylor123** [comment]
Hey @joeywongt3ch, this is likely because the contract size is 1. There should be more markets with the lower contract size (0.1 for ETH). Closing this for now, please re-open if that is not the issue
